spring:
  profiles:
    include:
      - db
      - batch

app:
  postal-code:
    url: https://zipcloud.ibsnet.co.jp/api/search

  aws:
    s3:
      url: ${AWS_S3_URL:http://127.0.0.1:9000}
      bucket: employee
      access-key: ${AWS_ACCESS_KEY_ID:minioadmin}
      secret-key: ${AWS_SECRET_ACCESS_KEY_ID:minioadmin}
    dynamo-db:
      url: ${AWS_S3_URL:http://127.0.0.1:8000}
      access-key: ${AWS_ACCESS_KEY_ID:dummy}
      secret-key: ${AWS_SECRET_ACCESS_KEY_ID:dummy}

  jwt:
    accessToken:
      expired-minutes: ${ACCESS_TOKEN_EXPIRED_TIME:60}
    refreshToken:
      expired-minutes: ${REFRESH_TOKEN_EXPIRED_TIME:240}
      length: ${REFRESH_TOKEN_LENGTH:120}
    secret: ${JWT_SECRET:gbservice}
    aud: ${JWT_AUD:https://gbservice.co.jp}
    sub: ${JWT_sub:gbs}

  role:
    deny-url:
      admin:
      manager:
        - method: POST
          url: /employee/calc_salary
        - method: DELETE
          url: /employee/.*
      general:
        - method: POST
          url: /employee/calc_salary
        - method: POST
          url: /employee
        - method: DELETE
          url: /employee/.*
  is2fa: true
  isDebug: true
  isLocal: true
  oneTimeToken:
    expiredAtTime: 5

logging:
  level:
    com:
      example:
        demo: DEBUG

