spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: admin
    password: admin
    driverClassName: com.mysql.jdbc.Driver

logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        demo:
          repository: DEBUG

app:
  postal-code:
    url: https://zipcloud.ibsnet.co.jp/api/search

  aws:
    s3:
      url: http://127.0.0.1:9000
      bucket: employee
      access-key: minioadmin
      secret-key: minioadmin
  rate:
    employment-increase: '0.003'
    welfare-increase: '0.20'