spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: admin
    password: admin
    driverClassName: com.mysql.jdbc.Driver

logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        demo:
          repository: DEBUG

app:
  postal-code:
    url: https://zipcloud.ibsnet.co.jp/api/search