spring:
  profiles:
    include:
      - db
      - batch

app:
  postal-code:
    url: https://zipcloud.ibsnet.co.jp/api/search

  aws:
    s3:
      url: ${AWS_S3_URL:http://127.0.0.1:9000}
      bucket: employee
      access-key: ${AWS_ACCESS_KEY_ID:minioadmin}
      secret-key: ${AWS_SECRET_ACCESS_KEY_ID:minioadmin}

  jwt:
    expired-hour: ${JWT_EXPIRED_HOUR:4}
    secret: ${JWT_SECRET:gbservice}
    aud: ${JWT_AUD:https://gbservice.co.jp}
    sub: ${JWT_sub:gbs}

