spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: admin
    password: admin
    driverClassName: com.mysql.jdbc.Driver

  batch:
    initialize-schema: always
    job:
      enabled: true
      names: demo
  level:
    org:
      springframework: DEBUG

app:
  rate:
    employment-increase: '0.003'
    welfare-increase: '0.20'