spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: admin
    password: admin
    driverClassName: com.mysql.jdbc.Driver

logging:
  level:
    com:
      example:
        demo:
          repository: DEBUG